/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OperatormainlayoutImport } from './routes/_operator_main_layout'
import { Route as ManagermainlayoutImport } from './routes/_manager_main_layout'
import { Route as AdminmainlayoutImport } from './routes/_admin_main_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'

// Create Virtual Routes

const OperatormainlayoutOperatorIndexLazyImport = createFileRoute(
  '/_operator_main_layout/operator/',
)()
const ManagermainlayoutManagerIndexLazyImport = createFileRoute(
  '/_manager_main_layout/manager/',
)()
const AdminmainlayoutAdminIndexLazyImport = createFileRoute(
  '/_admin_main_layout/admin/',
)()
const OperatormainlayoutOperatorVehicleMapLazyImport = createFileRoute(
  '/_operator_main_layout/operator/vehicle-map',
)()
const OperatormainlayoutOperatorRentalsLazyImport = createFileRoute(
  '/_operator_main_layout/operator/rentals',
)()
const OperatormainlayoutOperatorMalfunctionsLazyImport = createFileRoute(
  '/_operator_main_layout/operator/malfunctions',
)()
const OperatormainlayoutOperatorClientsLazyImport = createFileRoute(
  '/_operator_main_layout/operator/clients',
)()
const ManagermainlayoutManagerVehicleMapLazyImport = createFileRoute(
  '/_manager_main_layout/manager/vehicle-map',
)()
const ManagermainlayoutManagerUsersLazyImport = createFileRoute(
  '/_manager_main_layout/manager/users',
)()
const ManagermainlayoutManagerStatisticsLazyImport = createFileRoute(
  '/_manager_main_layout/manager/statistics',
)()
const ManagermainlayoutManagerRentalsLazyImport = createFileRoute(
  '/_manager_main_layout/manager/rentals',
)()
const ManagermainlayoutManagerRentalPricesLazyImport = createFileRoute(
  '/_manager_main_layout/manager/rental-prices',
)()
const ManagermainlayoutManagerManufacturersLazyImport = createFileRoute(
  '/_manager_main_layout/manager/manufacturers',
)()
const ManagermainlayoutManagerMalfunctionsLazyImport = createFileRoute(
  '/_manager_main_layout/manager/malfunctions',
)()
const ManagermainlayoutManagerClientsLazyImport = createFileRoute(
  '/_manager_main_layout/manager/clients',
)()
const AdminmainlayoutAdminUsersLazyImport = createFileRoute(
  '/_admin_main_layout/admin/users',
)()
const AdminmainlayoutAdminManufacturersLazyImport = createFileRoute(
  '/_admin_main_layout/admin/manufacturers',
)()
const ManagermainlayoutManagerVehiclesIndexLazyImport = createFileRoute(
  '/_manager_main_layout/manager/vehicles/',
)()
const AdminmainlayoutAdminVehiclesIndexLazyImport = createFileRoute(
  '/_admin_main_layout/admin/vehicles/',
)()
const ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyImport =
  createFileRoute('/_manager_main_layout/manager/vehicles/$vehicleId/details')()
const AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyImport = createFileRoute(
  '/_admin_main_layout/admin/vehicles/$vehicleId/details',
)()

// Create/Update Routes

const OperatormainlayoutRoute = OperatormainlayoutImport.update({
  id: '/_operator_main_layout',
  getParentRoute: () => rootRoute,
} as any)

const ManagermainlayoutRoute = ManagermainlayoutImport.update({
  id: '/_manager_main_layout',
  getParentRoute: () => rootRoute,
} as any)

const AdminmainlayoutRoute = AdminmainlayoutImport.update({
  id: '/_admin_main_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const OperatormainlayoutOperatorIndexLazyRoute =
  OperatormainlayoutOperatorIndexLazyImport.update({
    id: '/operator/',
    path: '/operator/',
    getParentRoute: () => OperatormainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_operator_main_layout/operator/index.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerIndexLazyRoute =
  ManagermainlayoutManagerIndexLazyImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminmainlayoutAdminIndexLazyRoute =
  AdminmainlayoutAdminIndexLazyImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AdminmainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_admin_main_layout/admin/index.lazy').then((d) => d.Route),
  )

const OperatormainlayoutOperatorVehicleMapLazyRoute =
  OperatormainlayoutOperatorVehicleMapLazyImport.update({
    id: '/operator/vehicle-map',
    path: '/operator/vehicle-map',
    getParentRoute: () => OperatormainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_operator_main_layout/operator/vehicle-map.lazy').then(
      (d) => d.Route,
    ),
  )

const OperatormainlayoutOperatorRentalsLazyRoute =
  OperatormainlayoutOperatorRentalsLazyImport.update({
    id: '/operator/rentals',
    path: '/operator/rentals',
    getParentRoute: () => OperatormainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_operator_main_layout/operator/rentals.lazy').then(
      (d) => d.Route,
    ),
  )

const OperatormainlayoutOperatorMalfunctionsLazyRoute =
  OperatormainlayoutOperatorMalfunctionsLazyImport.update({
    id: '/operator/malfunctions',
    path: '/operator/malfunctions',
    getParentRoute: () => OperatormainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_operator_main_layout/operator/malfunctions.lazy').then(
      (d) => d.Route,
    ),
  )

const OperatormainlayoutOperatorClientsLazyRoute =
  OperatormainlayoutOperatorClientsLazyImport.update({
    id: '/operator/clients',
    path: '/operator/clients',
    getParentRoute: () => OperatormainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_operator_main_layout/operator/clients.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerVehicleMapLazyRoute =
  ManagermainlayoutManagerVehicleMapLazyImport.update({
    id: '/manager/vehicle-map',
    path: '/manager/vehicle-map',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/vehicle-map.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerUsersLazyRoute =
  ManagermainlayoutManagerUsersLazyImport.update({
    id: '/manager/users',
    path: '/manager/users',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/users.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerStatisticsLazyRoute =
  ManagermainlayoutManagerStatisticsLazyImport.update({
    id: '/manager/statistics',
    path: '/manager/statistics',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/statistics.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerRentalsLazyRoute =
  ManagermainlayoutManagerRentalsLazyImport.update({
    id: '/manager/rentals',
    path: '/manager/rentals',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/rentals.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerRentalPricesLazyRoute =
  ManagermainlayoutManagerRentalPricesLazyImport.update({
    id: '/manager/rental-prices',
    path: '/manager/rental-prices',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/rental-prices.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerManufacturersLazyRoute =
  ManagermainlayoutManagerManufacturersLazyImport.update({
    id: '/manager/manufacturers',
    path: '/manager/manufacturers',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/manufacturers.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerMalfunctionsLazyRoute =
  ManagermainlayoutManagerMalfunctionsLazyImport.update({
    id: '/manager/malfunctions',
    path: '/manager/malfunctions',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/malfunctions.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerClientsLazyRoute =
  ManagermainlayoutManagerClientsLazyImport.update({
    id: '/manager/clients',
    path: '/manager/clients',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/clients.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminmainlayoutAdminUsersLazyRoute =
  AdminmainlayoutAdminUsersLazyImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AdminmainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_admin_main_layout/admin/users.lazy').then((d) => d.Route),
  )

const AdminmainlayoutAdminManufacturersLazyRoute =
  AdminmainlayoutAdminManufacturersLazyImport.update({
    id: '/admin/manufacturers',
    path: '/admin/manufacturers',
    getParentRoute: () => AdminmainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_admin_main_layout/admin/manufacturers.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerVehiclesIndexLazyRoute =
  ManagermainlayoutManagerVehiclesIndexLazyImport.update({
    id: '/manager/vehicles/',
    path: '/manager/vehicles/',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_manager_main_layout/manager/vehicles/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminmainlayoutAdminVehiclesIndexLazyRoute =
  AdminmainlayoutAdminVehiclesIndexLazyImport.update({
    id: '/admin/vehicles/',
    path: '/admin/vehicles/',
    getParentRoute: () => AdminmainlayoutRoute,
  } as any).lazy(() =>
    import('./routes/_admin_main_layout/admin/vehicles/index.lazy').then(
      (d) => d.Route,
    ),
  )

const ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute =
  ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyImport.update({
    id: '/manager/vehicles/$vehicleId/details',
    path: '/manager/vehicles/$vehicleId/details',
    getParentRoute: () => ManagermainlayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_manager_main_layout/manager/vehicles/$vehicleId/details.lazy'
    ).then((d) => d.Route),
  )

const AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute =
  AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyImport.update({
    id: '/admin/vehicles/$vehicleId/details',
    path: '/admin/vehicles/$vehicleId/details',
    getParentRoute: () => AdminmainlayoutRoute,
  } as any).lazy(() =>
    import(
      './routes/_admin_main_layout/admin/vehicles/$vehicleId/details.lazy'
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_admin_main_layout': {
      id: '/_admin_main_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminmainlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_manager_main_layout': {
      id: '/_manager_main_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ManagermainlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_operator_main_layout': {
      id: '/_operator_main_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OperatormainlayoutImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_admin_main_layout/admin/manufacturers': {
      id: '/_admin_main_layout/admin/manufacturers'
      path: '/admin/manufacturers'
      fullPath: '/admin/manufacturers'
      preLoaderRoute: typeof AdminmainlayoutAdminManufacturersLazyImport
      parentRoute: typeof AdminmainlayoutImport
    }
    '/_admin_main_layout/admin/users': {
      id: '/_admin_main_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminmainlayoutAdminUsersLazyImport
      parentRoute: typeof AdminmainlayoutImport
    }
    '/_manager_main_layout/manager/clients': {
      id: '/_manager_main_layout/manager/clients'
      path: '/manager/clients'
      fullPath: '/manager/clients'
      preLoaderRoute: typeof ManagermainlayoutManagerClientsLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/malfunctions': {
      id: '/_manager_main_layout/manager/malfunctions'
      path: '/manager/malfunctions'
      fullPath: '/manager/malfunctions'
      preLoaderRoute: typeof ManagermainlayoutManagerMalfunctionsLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/manufacturers': {
      id: '/_manager_main_layout/manager/manufacturers'
      path: '/manager/manufacturers'
      fullPath: '/manager/manufacturers'
      preLoaderRoute: typeof ManagermainlayoutManagerManufacturersLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/rental-prices': {
      id: '/_manager_main_layout/manager/rental-prices'
      path: '/manager/rental-prices'
      fullPath: '/manager/rental-prices'
      preLoaderRoute: typeof ManagermainlayoutManagerRentalPricesLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/rentals': {
      id: '/_manager_main_layout/manager/rentals'
      path: '/manager/rentals'
      fullPath: '/manager/rentals'
      preLoaderRoute: typeof ManagermainlayoutManagerRentalsLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/statistics': {
      id: '/_manager_main_layout/manager/statistics'
      path: '/manager/statistics'
      fullPath: '/manager/statistics'
      preLoaderRoute: typeof ManagermainlayoutManagerStatisticsLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/users': {
      id: '/_manager_main_layout/manager/users'
      path: '/manager/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagermainlayoutManagerUsersLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_manager_main_layout/manager/vehicle-map': {
      id: '/_manager_main_layout/manager/vehicle-map'
      path: '/manager/vehicle-map'
      fullPath: '/manager/vehicle-map'
      preLoaderRoute: typeof ManagermainlayoutManagerVehicleMapLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_operator_main_layout/operator/clients': {
      id: '/_operator_main_layout/operator/clients'
      path: '/operator/clients'
      fullPath: '/operator/clients'
      preLoaderRoute: typeof OperatormainlayoutOperatorClientsLazyImport
      parentRoute: typeof OperatormainlayoutImport
    }
    '/_operator_main_layout/operator/malfunctions': {
      id: '/_operator_main_layout/operator/malfunctions'
      path: '/operator/malfunctions'
      fullPath: '/operator/malfunctions'
      preLoaderRoute: typeof OperatormainlayoutOperatorMalfunctionsLazyImport
      parentRoute: typeof OperatormainlayoutImport
    }
    '/_operator_main_layout/operator/rentals': {
      id: '/_operator_main_layout/operator/rentals'
      path: '/operator/rentals'
      fullPath: '/operator/rentals'
      preLoaderRoute: typeof OperatormainlayoutOperatorRentalsLazyImport
      parentRoute: typeof OperatormainlayoutImport
    }
    '/_operator_main_layout/operator/vehicle-map': {
      id: '/_operator_main_layout/operator/vehicle-map'
      path: '/operator/vehicle-map'
      fullPath: '/operator/vehicle-map'
      preLoaderRoute: typeof OperatormainlayoutOperatorVehicleMapLazyImport
      parentRoute: typeof OperatormainlayoutImport
    }
    '/_admin_main_layout/admin/': {
      id: '/_admin_main_layout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminmainlayoutAdminIndexLazyImport
      parentRoute: typeof AdminmainlayoutImport
    }
    '/_manager_main_layout/manager/': {
      id: '/_manager_main_layout/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagermainlayoutManagerIndexLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_operator_main_layout/operator/': {
      id: '/_operator_main_layout/operator/'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatormainlayoutOperatorIndexLazyImport
      parentRoute: typeof OperatormainlayoutImport
    }
    '/_admin_main_layout/admin/vehicles/': {
      id: '/_admin_main_layout/admin/vehicles/'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminmainlayoutAdminVehiclesIndexLazyImport
      parentRoute: typeof AdminmainlayoutImport
    }
    '/_manager_main_layout/manager/vehicles/': {
      id: '/_manager_main_layout/manager/vehicles/'
      path: '/manager/vehicles'
      fullPath: '/manager/vehicles'
      preLoaderRoute: typeof ManagermainlayoutManagerVehiclesIndexLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
    '/_admin_main_layout/admin/vehicles/$vehicleId/details': {
      id: '/_admin_main_layout/admin/vehicles/$vehicleId/details'
      path: '/admin/vehicles/$vehicleId/details'
      fullPath: '/admin/vehicles/$vehicleId/details'
      preLoaderRoute: typeof AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyImport
      parentRoute: typeof AdminmainlayoutImport
    }
    '/_manager_main_layout/manager/vehicles/$vehicleId/details': {
      id: '/_manager_main_layout/manager/vehicles/$vehicleId/details'
      path: '/manager/vehicles/$vehicleId/details'
      fullPath: '/manager/vehicles/$vehicleId/details'
      preLoaderRoute: typeof ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyImport
      parentRoute: typeof ManagermainlayoutImport
    }
  }
}

// Create and export the route tree

interface AdminmainlayoutRouteChildren {
  AdminmainlayoutAdminManufacturersLazyRoute: typeof AdminmainlayoutAdminManufacturersLazyRoute
  AdminmainlayoutAdminUsersLazyRoute: typeof AdminmainlayoutAdminUsersLazyRoute
  AdminmainlayoutAdminIndexLazyRoute: typeof AdminmainlayoutAdminIndexLazyRoute
  AdminmainlayoutAdminVehiclesIndexLazyRoute: typeof AdminmainlayoutAdminVehiclesIndexLazyRoute
  AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute: typeof AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute
}

const AdminmainlayoutRouteChildren: AdminmainlayoutRouteChildren = {
  AdminmainlayoutAdminManufacturersLazyRoute:
    AdminmainlayoutAdminManufacturersLazyRoute,
  AdminmainlayoutAdminUsersLazyRoute: AdminmainlayoutAdminUsersLazyRoute,
  AdminmainlayoutAdminIndexLazyRoute: AdminmainlayoutAdminIndexLazyRoute,
  AdminmainlayoutAdminVehiclesIndexLazyRoute:
    AdminmainlayoutAdminVehiclesIndexLazyRoute,
  AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute:
    AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute,
}

const AdminmainlayoutRouteWithChildren = AdminmainlayoutRoute._addFileChildren(
  AdminmainlayoutRouteChildren,
)

interface ManagermainlayoutRouteChildren {
  ManagermainlayoutManagerClientsLazyRoute: typeof ManagermainlayoutManagerClientsLazyRoute
  ManagermainlayoutManagerMalfunctionsLazyRoute: typeof ManagermainlayoutManagerMalfunctionsLazyRoute
  ManagermainlayoutManagerManufacturersLazyRoute: typeof ManagermainlayoutManagerManufacturersLazyRoute
  ManagermainlayoutManagerRentalPricesLazyRoute: typeof ManagermainlayoutManagerRentalPricesLazyRoute
  ManagermainlayoutManagerRentalsLazyRoute: typeof ManagermainlayoutManagerRentalsLazyRoute
  ManagermainlayoutManagerStatisticsLazyRoute: typeof ManagermainlayoutManagerStatisticsLazyRoute
  ManagermainlayoutManagerUsersLazyRoute: typeof ManagermainlayoutManagerUsersLazyRoute
  ManagermainlayoutManagerVehicleMapLazyRoute: typeof ManagermainlayoutManagerVehicleMapLazyRoute
  ManagermainlayoutManagerIndexLazyRoute: typeof ManagermainlayoutManagerIndexLazyRoute
  ManagermainlayoutManagerVehiclesIndexLazyRoute: typeof ManagermainlayoutManagerVehiclesIndexLazyRoute
  ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute: typeof ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute
}

const ManagermainlayoutRouteChildren: ManagermainlayoutRouteChildren = {
  ManagermainlayoutManagerClientsLazyRoute:
    ManagermainlayoutManagerClientsLazyRoute,
  ManagermainlayoutManagerMalfunctionsLazyRoute:
    ManagermainlayoutManagerMalfunctionsLazyRoute,
  ManagermainlayoutManagerManufacturersLazyRoute:
    ManagermainlayoutManagerManufacturersLazyRoute,
  ManagermainlayoutManagerRentalPricesLazyRoute:
    ManagermainlayoutManagerRentalPricesLazyRoute,
  ManagermainlayoutManagerRentalsLazyRoute:
    ManagermainlayoutManagerRentalsLazyRoute,
  ManagermainlayoutManagerStatisticsLazyRoute:
    ManagermainlayoutManagerStatisticsLazyRoute,
  ManagermainlayoutManagerUsersLazyRoute:
    ManagermainlayoutManagerUsersLazyRoute,
  ManagermainlayoutManagerVehicleMapLazyRoute:
    ManagermainlayoutManagerVehicleMapLazyRoute,
  ManagermainlayoutManagerIndexLazyRoute:
    ManagermainlayoutManagerIndexLazyRoute,
  ManagermainlayoutManagerVehiclesIndexLazyRoute:
    ManagermainlayoutManagerVehiclesIndexLazyRoute,
  ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute:
    ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute,
}

const ManagermainlayoutRouteWithChildren =
  ManagermainlayoutRoute._addFileChildren(ManagermainlayoutRouteChildren)

interface OperatormainlayoutRouteChildren {
  OperatormainlayoutOperatorClientsLazyRoute: typeof OperatormainlayoutOperatorClientsLazyRoute
  OperatormainlayoutOperatorMalfunctionsLazyRoute: typeof OperatormainlayoutOperatorMalfunctionsLazyRoute
  OperatormainlayoutOperatorRentalsLazyRoute: typeof OperatormainlayoutOperatorRentalsLazyRoute
  OperatormainlayoutOperatorVehicleMapLazyRoute: typeof OperatormainlayoutOperatorVehicleMapLazyRoute
  OperatormainlayoutOperatorIndexLazyRoute: typeof OperatormainlayoutOperatorIndexLazyRoute
}

const OperatormainlayoutRouteChildren: OperatormainlayoutRouteChildren = {
  OperatormainlayoutOperatorClientsLazyRoute:
    OperatormainlayoutOperatorClientsLazyRoute,
  OperatormainlayoutOperatorMalfunctionsLazyRoute:
    OperatormainlayoutOperatorMalfunctionsLazyRoute,
  OperatormainlayoutOperatorRentalsLazyRoute:
    OperatormainlayoutOperatorRentalsLazyRoute,
  OperatormainlayoutOperatorVehicleMapLazyRoute:
    OperatormainlayoutOperatorVehicleMapLazyRoute,
  OperatormainlayoutOperatorIndexLazyRoute:
    OperatormainlayoutOperatorIndexLazyRoute,
}

const OperatormainlayoutRouteWithChildren =
  OperatormainlayoutRoute._addFileChildren(OperatormainlayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof OperatormainlayoutRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/manufacturers': typeof AdminmainlayoutAdminManufacturersLazyRoute
  '/admin/users': typeof AdminmainlayoutAdminUsersLazyRoute
  '/manager/clients': typeof ManagermainlayoutManagerClientsLazyRoute
  '/manager/malfunctions': typeof ManagermainlayoutManagerMalfunctionsLazyRoute
  '/manager/manufacturers': typeof ManagermainlayoutManagerManufacturersLazyRoute
  '/manager/rental-prices': typeof ManagermainlayoutManagerRentalPricesLazyRoute
  '/manager/rentals': typeof ManagermainlayoutManagerRentalsLazyRoute
  '/manager/statistics': typeof ManagermainlayoutManagerStatisticsLazyRoute
  '/manager/users': typeof ManagermainlayoutManagerUsersLazyRoute
  '/manager/vehicle-map': typeof ManagermainlayoutManagerVehicleMapLazyRoute
  '/operator/clients': typeof OperatormainlayoutOperatorClientsLazyRoute
  '/operator/malfunctions': typeof OperatormainlayoutOperatorMalfunctionsLazyRoute
  '/operator/rentals': typeof OperatormainlayoutOperatorRentalsLazyRoute
  '/operator/vehicle-map': typeof OperatormainlayoutOperatorVehicleMapLazyRoute
  '/admin': typeof AdminmainlayoutAdminIndexLazyRoute
  '/manager': typeof ManagermainlayoutManagerIndexLazyRoute
  '/operator': typeof OperatormainlayoutOperatorIndexLazyRoute
  '/admin/vehicles': typeof AdminmainlayoutAdminVehiclesIndexLazyRoute
  '/manager/vehicles': typeof ManagermainlayoutManagerVehiclesIndexLazyRoute
  '/admin/vehicles/$vehicleId/details': typeof AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute
  '/manager/vehicles/$vehicleId/details': typeof ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof OperatormainlayoutRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/manufacturers': typeof AdminmainlayoutAdminManufacturersLazyRoute
  '/admin/users': typeof AdminmainlayoutAdminUsersLazyRoute
  '/manager/clients': typeof ManagermainlayoutManagerClientsLazyRoute
  '/manager/malfunctions': typeof ManagermainlayoutManagerMalfunctionsLazyRoute
  '/manager/manufacturers': typeof ManagermainlayoutManagerManufacturersLazyRoute
  '/manager/rental-prices': typeof ManagermainlayoutManagerRentalPricesLazyRoute
  '/manager/rentals': typeof ManagermainlayoutManagerRentalsLazyRoute
  '/manager/statistics': typeof ManagermainlayoutManagerStatisticsLazyRoute
  '/manager/users': typeof ManagermainlayoutManagerUsersLazyRoute
  '/manager/vehicle-map': typeof ManagermainlayoutManagerVehicleMapLazyRoute
  '/operator/clients': typeof OperatormainlayoutOperatorClientsLazyRoute
  '/operator/malfunctions': typeof OperatormainlayoutOperatorMalfunctionsLazyRoute
  '/operator/rentals': typeof OperatormainlayoutOperatorRentalsLazyRoute
  '/operator/vehicle-map': typeof OperatormainlayoutOperatorVehicleMapLazyRoute
  '/admin': typeof AdminmainlayoutAdminIndexLazyRoute
  '/manager': typeof ManagermainlayoutManagerIndexLazyRoute
  '/operator': typeof OperatormainlayoutOperatorIndexLazyRoute
  '/admin/vehicles': typeof AdminmainlayoutAdminVehiclesIndexLazyRoute
  '/manager/vehicles': typeof ManagermainlayoutManagerVehiclesIndexLazyRoute
  '/admin/vehicles/$vehicleId/details': typeof AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute
  '/manager/vehicles/$vehicleId/details': typeof ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_admin_main_layout': typeof AdminmainlayoutRouteWithChildren
  '/_manager_main_layout': typeof ManagermainlayoutRouteWithChildren
  '/_operator_main_layout': typeof OperatormainlayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_admin_main_layout/admin/manufacturers': typeof AdminmainlayoutAdminManufacturersLazyRoute
  '/_admin_main_layout/admin/users': typeof AdminmainlayoutAdminUsersLazyRoute
  '/_manager_main_layout/manager/clients': typeof ManagermainlayoutManagerClientsLazyRoute
  '/_manager_main_layout/manager/malfunctions': typeof ManagermainlayoutManagerMalfunctionsLazyRoute
  '/_manager_main_layout/manager/manufacturers': typeof ManagermainlayoutManagerManufacturersLazyRoute
  '/_manager_main_layout/manager/rental-prices': typeof ManagermainlayoutManagerRentalPricesLazyRoute
  '/_manager_main_layout/manager/rentals': typeof ManagermainlayoutManagerRentalsLazyRoute
  '/_manager_main_layout/manager/statistics': typeof ManagermainlayoutManagerStatisticsLazyRoute
  '/_manager_main_layout/manager/users': typeof ManagermainlayoutManagerUsersLazyRoute
  '/_manager_main_layout/manager/vehicle-map': typeof ManagermainlayoutManagerVehicleMapLazyRoute
  '/_operator_main_layout/operator/clients': typeof OperatormainlayoutOperatorClientsLazyRoute
  '/_operator_main_layout/operator/malfunctions': typeof OperatormainlayoutOperatorMalfunctionsLazyRoute
  '/_operator_main_layout/operator/rentals': typeof OperatormainlayoutOperatorRentalsLazyRoute
  '/_operator_main_layout/operator/vehicle-map': typeof OperatormainlayoutOperatorVehicleMapLazyRoute
  '/_admin_main_layout/admin/': typeof AdminmainlayoutAdminIndexLazyRoute
  '/_manager_main_layout/manager/': typeof ManagermainlayoutManagerIndexLazyRoute
  '/_operator_main_layout/operator/': typeof OperatormainlayoutOperatorIndexLazyRoute
  '/_admin_main_layout/admin/vehicles/': typeof AdminmainlayoutAdminVehiclesIndexLazyRoute
  '/_manager_main_layout/manager/vehicles/': typeof ManagermainlayoutManagerVehiclesIndexLazyRoute
  '/_admin_main_layout/admin/vehicles/$vehicleId/details': typeof AdminmainlayoutAdminVehiclesVehicleIdDetailsLazyRoute
  '/_manager_main_layout/manager/vehicles/$vehicleId/details': typeof ManagermainlayoutManagerVehiclesVehicleIdDetailsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/admin/manufacturers'
    | '/admin/users'
    | '/manager/clients'
    | '/manager/malfunctions'
    | '/manager/manufacturers'
    | '/manager/rental-prices'
    | '/manager/rentals'
    | '/manager/statistics'
    | '/manager/users'
    | '/manager/vehicle-map'
    | '/operator/clients'
    | '/operator/malfunctions'
    | '/operator/rentals'
    | '/operator/vehicle-map'
    | '/admin'
    | '/manager'
    | '/operator'
    | '/admin/vehicles'
    | '/manager/vehicles'
    | '/admin/vehicles/$vehicleId/details'
    | '/manager/vehicles/$vehicleId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/admin/manufacturers'
    | '/admin/users'
    | '/manager/clients'
    | '/manager/malfunctions'
    | '/manager/manufacturers'
    | '/manager/rental-prices'
    | '/manager/rentals'
    | '/manager/statistics'
    | '/manager/users'
    | '/manager/vehicle-map'
    | '/operator/clients'
    | '/operator/malfunctions'
    | '/operator/rentals'
    | '/operator/vehicle-map'
    | '/admin'
    | '/manager'
    | '/operator'
    | '/admin/vehicles'
    | '/manager/vehicles'
    | '/admin/vehicles/$vehicleId/details'
    | '/manager/vehicles/$vehicleId/details'
  id:
    | '__root__'
    | '/'
    | '/_admin_main_layout'
    | '/_manager_main_layout'
    | '/_operator_main_layout'
    | '/login/'
    | '/_admin_main_layout/admin/manufacturers'
    | '/_admin_main_layout/admin/users'
    | '/_manager_main_layout/manager/clients'
    | '/_manager_main_layout/manager/malfunctions'
    | '/_manager_main_layout/manager/manufacturers'
    | '/_manager_main_layout/manager/rental-prices'
    | '/_manager_main_layout/manager/rentals'
    | '/_manager_main_layout/manager/statistics'
    | '/_manager_main_layout/manager/users'
    | '/_manager_main_layout/manager/vehicle-map'
    | '/_operator_main_layout/operator/clients'
    | '/_operator_main_layout/operator/malfunctions'
    | '/_operator_main_layout/operator/rentals'
    | '/_operator_main_layout/operator/vehicle-map'
    | '/_admin_main_layout/admin/'
    | '/_manager_main_layout/manager/'
    | '/_operator_main_layout/operator/'
    | '/_admin_main_layout/admin/vehicles/'
    | '/_manager_main_layout/manager/vehicles/'
    | '/_admin_main_layout/admin/vehicles/$vehicleId/details'
    | '/_manager_main_layout/manager/vehicles/$vehicleId/details'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminmainlayoutRoute: typeof AdminmainlayoutRouteWithChildren
  ManagermainlayoutRoute: typeof ManagermainlayoutRouteWithChildren
  OperatormainlayoutRoute: typeof OperatormainlayoutRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminmainlayoutRoute: AdminmainlayoutRouteWithChildren,
  ManagermainlayoutRoute: ManagermainlayoutRouteWithChildren,
  OperatormainlayoutRoute: OperatormainlayoutRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_admin_main_layout",
        "/_manager_main_layout",
        "/_operator_main_layout",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_admin_main_layout": {
      "filePath": "_admin_main_layout.tsx",
      "children": [
        "/_admin_main_layout/admin/manufacturers",
        "/_admin_main_layout/admin/users",
        "/_admin_main_layout/admin/",
        "/_admin_main_layout/admin/vehicles/",
        "/_admin_main_layout/admin/vehicles/$vehicleId/details"
      ]
    },
    "/_manager_main_layout": {
      "filePath": "_manager_main_layout.tsx",
      "children": [
        "/_manager_main_layout/manager/clients",
        "/_manager_main_layout/manager/malfunctions",
        "/_manager_main_layout/manager/manufacturers",
        "/_manager_main_layout/manager/rental-prices",
        "/_manager_main_layout/manager/rentals",
        "/_manager_main_layout/manager/statistics",
        "/_manager_main_layout/manager/users",
        "/_manager_main_layout/manager/vehicle-map",
        "/_manager_main_layout/manager/",
        "/_manager_main_layout/manager/vehicles/",
        "/_manager_main_layout/manager/vehicles/$vehicleId/details"
      ]
    },
    "/_operator_main_layout": {
      "filePath": "_operator_main_layout.tsx",
      "children": [
        "/_operator_main_layout/operator/clients",
        "/_operator_main_layout/operator/malfunctions",
        "/_operator_main_layout/operator/rentals",
        "/_operator_main_layout/operator/vehicle-map",
        "/_operator_main_layout/operator/"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_admin_main_layout/admin/manufacturers": {
      "filePath": "_admin_main_layout/admin/manufacturers.lazy.tsx",
      "parent": "/_admin_main_layout"
    },
    "/_admin_main_layout/admin/users": {
      "filePath": "_admin_main_layout/admin/users.lazy.tsx",
      "parent": "/_admin_main_layout"
    },
    "/_manager_main_layout/manager/clients": {
      "filePath": "_manager_main_layout/manager/clients.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/malfunctions": {
      "filePath": "_manager_main_layout/manager/malfunctions.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/manufacturers": {
      "filePath": "_manager_main_layout/manager/manufacturers.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/rental-prices": {
      "filePath": "_manager_main_layout/manager/rental-prices.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/rentals": {
      "filePath": "_manager_main_layout/manager/rentals.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/statistics": {
      "filePath": "_manager_main_layout/manager/statistics.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/users": {
      "filePath": "_manager_main_layout/manager/users.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_manager_main_layout/manager/vehicle-map": {
      "filePath": "_manager_main_layout/manager/vehicle-map.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_operator_main_layout/operator/clients": {
      "filePath": "_operator_main_layout/operator/clients.lazy.tsx",
      "parent": "/_operator_main_layout"
    },
    "/_operator_main_layout/operator/malfunctions": {
      "filePath": "_operator_main_layout/operator/malfunctions.lazy.tsx",
      "parent": "/_operator_main_layout"
    },
    "/_operator_main_layout/operator/rentals": {
      "filePath": "_operator_main_layout/operator/rentals.lazy.tsx",
      "parent": "/_operator_main_layout"
    },
    "/_operator_main_layout/operator/vehicle-map": {
      "filePath": "_operator_main_layout/operator/vehicle-map.lazy.tsx",
      "parent": "/_operator_main_layout"
    },
    "/_admin_main_layout/admin/": {
      "filePath": "_admin_main_layout/admin/index.lazy.tsx",
      "parent": "/_admin_main_layout"
    },
    "/_manager_main_layout/manager/": {
      "filePath": "_manager_main_layout/manager/index.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_operator_main_layout/operator/": {
      "filePath": "_operator_main_layout/operator/index.lazy.tsx",
      "parent": "/_operator_main_layout"
    },
    "/_admin_main_layout/admin/vehicles/": {
      "filePath": "_admin_main_layout/admin/vehicles/index.lazy.tsx",
      "parent": "/_admin_main_layout"
    },
    "/_manager_main_layout/manager/vehicles/": {
      "filePath": "_manager_main_layout/manager/vehicles/index.lazy.tsx",
      "parent": "/_manager_main_layout"
    },
    "/_admin_main_layout/admin/vehicles/$vehicleId/details": {
      "filePath": "_admin_main_layout/admin/vehicles/$vehicleId/details.lazy.tsx",
      "parent": "/_admin_main_layout"
    },
    "/_manager_main_layout/manager/vehicles/$vehicleId/details": {
      "filePath": "_manager_main_layout/manager/vehicles/$vehicleId/details.lazy.tsx",
      "parent": "/_manager_main_layout"
    }
  }
}
ROUTE_MANIFEST_END */
